### ISSUE TITLE
More public votes

### ISSUE THREAD

**Issue by Gorilliath** [Gorilliath/CMW-ImbaMod#15]
No more dependence on admins to do something as basic as toggling tournament mode

**Comment by RufusPitt** [comment]
vote rankedmode 1
vote rankedteamsize #
vote tournamentmode 1

"just replace admin with vote in the command"
as suggested by lyon

**Comment by Gorilliath** [comment]
Blocked by #38

**Comment by Gorilliath** [comment]
No longer blocked by #38
