### ISSUE TITLE
Record more player stats

### ISSUE THREAD

**Issue by Gorilliath** [Gorilliath/CMW-ImbaMod#41]
- [x] Total health lost
- [x] Total stamina spent
- [x] Damage received from teammates
- [x] Stamina damage
- [x] Health regenerated
- [x] Stamina regenerated
- [x] Parried attacks
- [x] Blocked attacks
- [x] Melee hits
- [x] Projectile hits
- [x] Light shove hits
- [x] Heavy shove hits
- [x] Feints
- [x] Crouch
- [x] Jumps
- [x] Dodges
- [x] Chatter (Battlecry, VO)

**Comment by RufusPitt** [comment]
![image](https://user-images.githubusercontent.com/57277756/124940337-ce8f0280-e001-11eb-91ec-6d6fadb5d7fa.png)
